name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: >
          sudo apt-get update -y \
            && sudo apt-get upgrade -y \
            && sudo apt-get install -y python3-pip \
            && pip3 install --user vim-vint

      - name: lint
        run: ~/.local/bin/vint **/*.vim
